"""empty message

Revision ID: 00dc1fce166b
Revises: 9ab148541228
Create Date: 2021-04-14 01:47:10.991147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dc1fce166b'
down_revision = '9ab148541228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['speciality.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('appointment', sa.Column('specialist_id', sa.Integer(), nullable=False))
    op.add_column('appointment', sa.Column('speciality_id', sa.Integer(), nullable=False))
    op.add_column('appointment', sa.Column('time', sa.Time(), nullable=False))
    op.create_foreign_key(None, 'appointment', 'specialist', ['specialist_id'], ['id'])
    op.create_foreign_key(None, 'appointment', 'speciality', ['speciality_id'], ['id'])
    op.drop_column('appointment', 'specialist')
    op.drop_column('appointment', 'speciality')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('speciality', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.add_column('appointment', sa.Column('specialist', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'time')
    op.drop_column('appointment', 'speciality_id')
    op.drop_column('appointment', 'specialist_id')
    op.drop_table('time')
    # ### end Alembic commands ###
