"""empty message

Revision ID: 142623082450
Revises: 72224f94068c
Create Date: 2021-05-08 18:40:08.553880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142623082450'
down_revision = '72224f94068c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
