"""empty message

Revision ID: 1d4bfdc1b941
Revises: 44267301baee
Create Date: 2021-04-05 15:20:45.531222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4bfdc1b941'
down_revision = '44267301baee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
