"""empty message

Revision ID: 23c64dd508f2
Revises: 142623082450
Create Date: 2021-05-09 14:11:55.332367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c64dd508f2'
down_revision = '142623082450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('user', '_password')
    # ### end Alembic commands ###
