"""empty message

Revision ID: 2d87b357c30d
Revises: 9ab148541228
Create Date: 2021-04-09 03:30:46.145510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d87b357c30d'
down_revision = '9ab148541228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('rol_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'rol', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'rol_id')
    op.drop_table('rol')
    # ### end Alembic commands ###
