"""empty message

Revision ID: 44267301baee
Revises: ce72c028f03f
Create Date: 2021-04-05 00:02:03.344940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44267301baee'
down_revision = 'ce72c028f03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'specialist', ['id'])
    op.create_unique_constraint(None, 'speciality', ['id'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'speciality', type_='unique')
    op.drop_constraint(None, 'specialist', type_='unique')
    # ### end Alembic commands ###
