"""empty message

Revision ID: 4e607615d439
Revises: fbb1bf6ed66a
Create Date: 2021-04-23 01:58:53.756334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e607615d439'
down_revision = 'fbb1bf6ed66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'appointment', ['id'])
    op.create_unique_constraint(None, 'specialist', ['id'])
    op.create_unique_constraint(None, 'speciality', ['id'])
    op.add_column('user', sa.Column('reset_password', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'working_hours', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_hours', type_='unique')
    op.drop_column('user', 'reset_password')
    op.drop_constraint(None, 'speciality', type_='unique')
    op.drop_constraint(None, 'specialist', type_='unique')
    op.drop_constraint(None, 'appointment', type_='unique')
    # ### end Alembic commands ###
