"""empty message

Revision ID: 87d31face039
Revises: 5662e998d2c3
Create Date: 2021-04-01 18:53:46.118253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d31face039'
down_revision = '5662e998d2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('pet', sa.String(length=250), nullable=False))
    op.add_column('appointment', sa.Column('pet_name', sa.String(length=250), nullable=False))
    op.add_column('appointment', sa.Column('specialist', sa.String(length=250), nullable=False))
    op.add_column('appointment', sa.Column('speciality', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'appointment', ['id'])
    op.drop_column('appointment', 'end_time')
    op.drop_column('appointment', 'start_time')
    op.drop_column('appointment', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('appointment', sa.Column('start_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('appointment', sa.Column('end_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointment', type_='unique')
    op.drop_column('appointment', 'speciality')
    op.drop_column('appointment', 'specialist')
    op.drop_column('appointment', 'pet_name')
    op.drop_column('appointment', 'pet')
    # ### end Alembic commands ###
