"""empty message

Revision ID: 9ab148541228
Revises: 633157717e3f
Create Date: 2021-04-07 13:41:11.247495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab148541228'
down_revision = '633157717e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'appointment', ['id'])
    op.create_unique_constraint(None, 'specialist', ['id'])
    op.create_unique_constraint(None, 'speciality', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speciality', type_='unique')
    op.drop_constraint(None, 'specialist', type_='unique')
    op.drop_constraint(None, 'appointment', type_='unique')
    # ### end Alembic commands ###
