"""empty message

Revision ID: a939d9ce3331
Revises: d6de0878e270
Create Date: 2021-05-08 18:37:10.042810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a939d9ce3331'
down_revision = 'd6de0878e270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'appointment', ['id'])
    op.create_unique_constraint(None, 'perfil', ['id'])
    op.create_unique_constraint(None, 'specialist', ['id'])
    op.create_unique_constraint(None, 'speciality', ['id'])
    op.add_column('user', sa.Column('password', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'working_hours', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_hours', type_='unique')
    op.drop_column('user', 'password')
    op.drop_constraint(None, 'speciality', type_='unique')
    op.drop_constraint(None, 'specialist', type_='unique')
    op.drop_constraint(None, 'perfil', type_='unique')
    op.drop_constraint(None, 'appointment', type_='unique')
    # ### end Alembic commands ###
