"""empty message

Revision ID: f5a5d5c32a2c
Revises: 00dc1fce166b
Create Date: 2021-04-15 02:33:27.768179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5a5d5c32a2c'
down_revision = '00dc1fce166b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['speciality.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('speciality_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['speciality_id'], ['speciality.id'], name='time_speciality_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='time_pkey')
    )
    op.drop_table('working_hours')
    # ### end Alembic commands ###
